### ISSUE TITLE
Update Tests for better pandas df snapshots

### ISSUE THREAD

**Issue by jcharkow** [Roestlab/massdash#112]
Issue:

Currently, snapshots using a pandas dataframe seem to be broken to me as it is not actually checking the entire dataframe just sections of this. 

![image](https://github.com/Roestlab/massdash/assets/47336288/ba389d6a-b015-48d2-805b-f7b45277ca4f)

One option I've considered is converting to dictionaries however sometimes tests still fail because dictionaries have no order in their columns. 

Currently, the best solution I can find is using a custom extension of syrupy which allows for snapshots with pandas dataframes. I am currently working on that in the https://github.com/Roestlab/massdash/tree/test/add_tests branch.

This would require additional dependencies of pytest and syrupy however I think it is worth it. @singjc @irahorecka please let me know your thoughts

**Comment by singjc** [comment]
@jcharkow @irahorecka I think we should add unittests for the main stream app as well.

https://docs.streamlit.io/library/api-reference/app-testing

**Comment by jcharkow** [comment]
I am working on this in https://github.com/Roestlab/massdash/tree/test/gui_tests

**Comment by jcharkow** [comment]
Closing this because Pandas Df snapshots have been added. Note: We still have to do streamlit tests
