### ISSUE TITLE
Readme python versions incorrect

### ISSUE THREAD

**Issue by jcharkow** [Roestlab/massdash#120]
Python 3.8 is not supported. Also python 3.12 is not tested so we don't know if that is supported. Update image badge on readme to reflect this.

**Comment by jcharkow** [comment]
@singjc would you be able to fix this?

**Comment by singjc** [comment]
> @singjc would you be able to fix this?

I believe Ira already updated the project.toml and setup.cfg to specify Python 3.9, 3.10 and 3.11. PyPi (and the badges) won't be updated until we push a new release. Do we want to push a new release now, or once all the final tests / PRs are merged?
