### ISSUE TITLE
[REFACTOR] Logging

### ISSUE THREAD

**Issue by singjc** [Roestlab/massdash#46]
Need to refactor and improve logging

**Comment by jcharkow** [comment]
is this complete?

**Comment by singjc** [comment]
> is this complete?

For the most part, I think so. What do you think about the current logging? Are there any additional places that require it?

**Comment by jcharkow** [comment]
I think there are some places that take verbose arguments that do not use however I think overall we are at a good spot?

**Comment by singjc** [comment]
> I think there are some places that take verbose arguments that do not use however I think overall we are at a good spot?

Yip I think so, can close this then
